---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-deployment
  labels:
    app: go-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-rest
  template:
    metadata:
      labels:
        app: go-rest
    spec:
      containers:
      - image: lumow/golang-web-server:latest
        name: go-rest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-rest-service
spec:
  type: LoadBalancer
  selector:
    app: go-rest
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
